# Generated by Django 4.2 on 2023-04-13 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=19)),
                ('lastName', models.CharField(max_length=19)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentName', models.CharField(choices=[('HW', 'Height/Weight'), ('BP', 'Blood Pressure'), ('HR', 'Heart Rate')], max_length=50)),
                ('componentVaue', models.CharField(max_length=50)),
                ('measuredDateTime', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clincApp.patient')),
            ],
        ),
    ]
