# Generated by Django 4.2 on 2023-04-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clincApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='componentVaue',
            new_name='componentValue',
        ),
    ]
